#!/bin/bash
set -e +x

echo "Running pre-commit hooks checks"

# Run gitleaks checks
if ! just -q gitleaks-detect; then
  echo "Warning: gitleaks-detect command failed"
  exit 1
else
  echo "gitleaks checks passed"
fi

# Run prettier checks
if ! just -q prettier-check; then
  echo "Warning: prettier-check command failed"
  exit 1
else
  echo "prettier checks passed"
fi

echo "All pre-commit hooks checks passed"
