# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "*.md", "docs/**"]
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [
                "docs/*.md",
                "*.md",
                "LICENCE",
                ".github/pull_request_template.md",
              ]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/uv.lock"]
      - head-branch: ["^dependabot"]
challenge:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["challenges/**/*"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile", "**/*.just"]
shell:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/*.sh", "pre-commit", "post-commit"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/workflows/*", ".github/actions/*"]
git_hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["githooks/**"]
