name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  packages: read

env:
  FORCE_COLOR: 1

jobs:
  common-code-checks:
    name: Common Code Checks
    permissions:
      contents: read
      actions: read
      pull-requests: write
      security-events: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml@69995069a0036cef69ac3cc2abf89f1376053a52 # v2025.08.26.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}

  run-python-lint-checks:
    name: Run Python Lint Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Generate Ruff Sarif
        run: just ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3.30.3
        with:
          sarif_file: ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Linting (Ruff)
        run: just ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-format-checks:
    name: Run Python Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Check Python Code Format (Ruff)
        run: just ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-python-type-checks:
    name: Run Python Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Check Python Code Types (ty) Checks
        run: just ty-check

  run-python-lockfile-check:
    name: Run Python Lockfile Check
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Check UV Lockfile
        run: just uv-lock-check

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Run Unit Tests
        run: just test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codeql-checks:
    name: CodeQL Analysis
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [actions, python]
    uses: JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml@69995069a0036cef69ac3cc2abf89f1376053a52 # v2025.08.26.01
    with:
      language: ${{ matrix.language }}
